server.port=8081
spring.application.name=student-service-platform

external.ai-service.base-url=http://10.47.211.117:8000
external.warning-service.base-url=http://10.47.211.117:8002

spring.datasource.driver-class-name=com.kingbase8.Driver
spring.datasource.url=jdbc:kingbase8://localhost:54321/student_platform
spring.datasource.username=你的数据库用户名
spring.datasource.password=你的数据库密码